sqlalchemy.exc.InvalidRequestError: Class <class 'app.models.Acquisto'> does not have a __table__ or __tablename__ specified and does not inherit from an existing table-mapped class.